// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RectArgs struct {
	Width                float64  `protobuf:"fixed64,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               float64  `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RectArgs) Reset()         { *m = RectArgs{} }
func (m *RectArgs) String() string { return proto.CompactTextString(m) }
func (*RectArgs) ProtoMessage()    {}
func (*RectArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_39bf00d4623c485e, []int{0}
}
func (m *RectArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RectArgs.Unmarshal(m, b)
}
func (m *RectArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RectArgs.Marshal(b, m, deterministic)
}
func (dst *RectArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RectArgs.Merge(dst, src)
}
func (m *RectArgs) XXX_Size() int {
	return xxx_messageInfo_RectArgs.Size(m)
}
func (m *RectArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RectArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RectArgs proto.InternalMessageInfo

func (m *RectArgs) GetWidth() float64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *RectArgs) GetHeight() float64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type RectReply struct {
	Perimeter            float64  `protobuf:"fixed64,1,opt,name=perimeter,proto3" json:"perimeter,omitempty"`
	Square               float64  `protobuf:"fixed64,2,opt,name=square,proto3" json:"square,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RectReply) Reset()         { *m = RectReply{} }
func (m *RectReply) String() string { return proto.CompactTextString(m) }
func (*RectReply) ProtoMessage()    {}
func (*RectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_39bf00d4623c485e, []int{1}
}
func (m *RectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RectReply.Unmarshal(m, b)
}
func (m *RectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RectReply.Marshal(b, m, deterministic)
}
func (dst *RectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RectReply.Merge(dst, src)
}
func (m *RectReply) XXX_Size() int {
	return xxx_messageInfo_RectReply.Size(m)
}
func (m *RectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RectReply.DiscardUnknown(m)
}

var xxx_messageInfo_RectReply proto.InternalMessageInfo

func (m *RectReply) GetPerimeter() float64 {
	if m != nil {
		return m.Perimeter
	}
	return 0
}

func (m *RectReply) GetSquare() float64 {
	if m != nil {
		return m.Square
	}
	return 0
}

type CircleArgs struct {
	Radius               float64  `protobuf:"fixed64,1,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CircleArgs) Reset()         { *m = CircleArgs{} }
func (m *CircleArgs) String() string { return proto.CompactTextString(m) }
func (*CircleArgs) ProtoMessage()    {}
func (*CircleArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_39bf00d4623c485e, []int{2}
}
func (m *CircleArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircleArgs.Unmarshal(m, b)
}
func (m *CircleArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircleArgs.Marshal(b, m, deterministic)
}
func (dst *CircleArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircleArgs.Merge(dst, src)
}
func (m *CircleArgs) XXX_Size() int {
	return xxx_messageInfo_CircleArgs.Size(m)
}
func (m *CircleArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_CircleArgs.DiscardUnknown(m)
}

var xxx_messageInfo_CircleArgs proto.InternalMessageInfo

func (m *CircleArgs) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type CircleReply struct {
	Length               float64  `protobuf:"fixed64,1,opt,name=length,proto3" json:"length,omitempty"`
	Square               float64  `protobuf:"fixed64,2,opt,name=square,proto3" json:"square,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CircleReply) Reset()         { *m = CircleReply{} }
func (m *CircleReply) String() string { return proto.CompactTextString(m) }
func (*CircleReply) ProtoMessage()    {}
func (*CircleReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_39bf00d4623c485e, []int{3}
}
func (m *CircleReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircleReply.Unmarshal(m, b)
}
func (m *CircleReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircleReply.Marshal(b, m, deterministic)
}
func (dst *CircleReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircleReply.Merge(dst, src)
}
func (m *CircleReply) XXX_Size() int {
	return xxx_messageInfo_CircleReply.Size(m)
}
func (m *CircleReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CircleReply.DiscardUnknown(m)
}

var xxx_messageInfo_CircleReply proto.InternalMessageInfo

func (m *CircleReply) GetLength() float64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *CircleReply) GetSquare() float64 {
	if m != nil {
		return m.Square
	}
	return 0
}

func init() {
	proto.RegisterType((*RectArgs)(nil), "service.RectArgs")
	proto.RegisterType((*RectReply)(nil), "service.RectReply")
	proto.RegisterType((*CircleArgs)(nil), "service.CircleArgs")
	proto.RegisterType((*CircleReply)(nil), "service.CircleReply")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_39bf00d4623c485e) }

var fileDescriptor_service_39bf00d4623c485e = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xb1, 0x0e, 0x82, 0x30,
	0x10, 0x86, 0x83, 0x89, 0x55, 0xce, 0xb8, 0x34, 0x86, 0x30, 0x38, 0x98, 0xc6, 0xc1, 0xc9, 0xc5,
	0xc5, 0xc5, 0x81, 0xf8, 0x06, 0xbc, 0x01, 0xc2, 0x05, 0x2e, 0x41, 0xc1, 0x6b, 0xd1, 0xf8, 0xf6,
	0x86, 0xf6, 0xd4, 0xc9, 0xf1, 0xfb, 0xd3, 0xff, 0xff, 0x7a, 0xb0, 0xb4, 0xc8, 0x0f, 0x2a, 0x71,
	0xdf, 0x73, 0xe7, 0x3a, 0x3d, 0x13, 0x34, 0x47, 0x98, 0xe7, 0x58, 0xba, 0x8c, 0x6b, 0xab, 0x57,
	0x30, 0x7d, 0x52, 0xe5, 0x9a, 0x34, 0xda, 0x44, 0xbb, 0x28, 0x0f, 0xa0, 0x13, 0x50, 0x0d, 0x52,
	0xdd, 0xb8, 0x74, 0xe2, 0x63, 0x21, 0x93, 0x41, 0x3c, 0x36, 0x73, 0xec, 0xdb, 0x97, 0x5e, 0x43,
	0xdc, 0x23, 0xd3, 0x15, 0x1d, 0xb2, 0xd4, 0x7f, 0xc1, 0x38, 0x61, 0xef, 0x43, 0xc1, 0xf8, 0x99,
	0x08, 0x64, 0xb6, 0x00, 0x67, 0xe2, 0xb2, 0x45, 0xaf, 0x4f, 0x40, 0x71, 0x51, 0xd1, 0x60, 0x65,
	0x40, 0xc8, 0x9c, 0x60, 0x11, 0x5e, 0x05, 0x55, 0x02, 0xaa, 0xc5, 0x5b, 0xfd, 0xfd, 0xa6, 0xd0,
	0x3f, 0xc9, 0x45, 0xf9, 0x8b, 0x0f, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x83, 0x64, 0x5a, 0x31,
	0x02, 0x01, 0x00, 0x00,
}
