// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status.proto

package status

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status struct {
	Code                 uint32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_dc0838ab51862bef, []int{0}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "xnats.status.Status")
	proto.RegisterMapType((map[string]string)(nil), "xnats.status.Status.MetaEntry")
}

func init() { proto.RegisterFile("status.proto", fileDescriptor_status_dc0838ab51862bef) }

var fileDescriptor_status_dc0838ab51862bef = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xa9, 0xc8, 0x4b, 0x2c, 0x29, 0xd6,
	0x83, 0x88, 0x29, 0x2d, 0x66, 0xe4, 0x62, 0x0b, 0x06, 0x33, 0x85, 0x84, 0xb8, 0x58, 0x92, 0xf3,
	0x53, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xdc,
	0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0xc8,
	0x88, 0x8b, 0x25, 0x37, 0xb5, 0x24, 0x51, 0x82, 0x59, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x4e, 0x0f,
	0xd9, 0x54, 0x3d, 0x88, 0x89, 0x7a, 0xbe, 0xa9, 0x25, 0x89, 0xae, 0x79, 0x25, 0x45, 0x95, 0x41,
	0x60, 0xb5, 0x52, 0xe6, 0x5c, 0x9c, 0x70, 0x21, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0xb0,
	0x6d, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x29, 0xcc, 0x2a, 0x08,
	0xc7, 0x8a, 0xc9, 0x82, 0xd1, 0x89, 0x23, 0x8a, 0x0d, 0x62, 0x72, 0x12, 0x1b, 0xd8, 0x13, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xe4, 0x99, 0xbf, 0xd4, 0x00, 0x00, 0x00,
}
